/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fatec.poo.view;

import fatec.poo.control.DaoHotel;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Hotel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class GuiCadastroHotel extends javax.swing.JFrame {

  /**
   * Creates new form CadastroHotel
   */
  public GuiCadastroHotel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    txtNome = new javax.swing.JTextField();
    txtCod = new javax.swing.JTextField();
    txtTelefone = new javax.swing.JTextField();
    txtEndereco = new javax.swing.JTextField();
    txtTotalFat = new javax.swing.JTextField();
    txtValDiaria = new javax.swing.JTextField();
    btnConsultar = new javax.swing.JButton();
    btnIncluir = new javax.swing.JButton();
    btnSair = new javax.swing.JButton();
    btnAlterar = new javax.swing.JButton();
    btnExcluir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(
      new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
          formWindowOpened(evt);
        }
      }
    );

    jLabel1.setText("Código");

    jLabel2.setText("Endereço");

    jLabel3.setText("Nome");

    jLabel4.setText("Telefone");

    jLabel5.setText("Valor Diária");

    jLabel6.setText("Total Faturamento");

    txtNome.setEnabled(false);

    txtTelefone.setEnabled(false);

    txtEndereco.setEnabled(false);

    txtTotalFat.setEnabled(false);

    txtValDiaria.setEnabled(false);

    btnConsultar.setText("Consultar");
    btnConsultar.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnConsultarActionPerformed(evt);
        }
      }
    );

    btnIncluir.setText("Incluir");
    btnIncluir.setEnabled(false);
    btnIncluir.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnIncluirActionPerformed(evt);
        }
      }
    );

    btnSair.setText("Sair");
    btnSair.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnSairActionPerformed(evt);
        }
      }
    );

    btnAlterar.setText("Alterar");
    btnAlterar.setEnabled(false);
    btnAlterar.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnAlterarActionPerformed(evt);
        }
      }
    );

    btnExcluir.setText("Excluir");
    btnExcluir.setEnabled(false);
    btnExcluir.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnExcluirActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(btnConsultar)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      15,
                      Short.MAX_VALUE
                    )
                    .addComponent(btnIncluir)
                    .addGap(18, 18, 18)
                    .addComponent(btnAlterar)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                    )
                    .addComponent(btnExcluir)
                    .addGap(7, 7, 7)
                    .addComponent(btnSair)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(
                              jLabel1,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              43,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                            )
                            .addComponent(
                              txtCod,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              71,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(
                              javax.swing.LayoutStyle.ComponentPlacement.RELATED
                            )
                            .addComponent(
                              txtTotalFat,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              71,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGroup(
                          layout
                            .createSequentialGroup()
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(
                                  jLabel3,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  37,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(jLabel2)
                            )
                            .addGap(18, 18, 18)
                            .addGroup(
                              layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  false
                                )
                                .addComponent(
                                  txtNome,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  237,
                                  Short.MAX_VALUE
                                )
                                .addComponent(txtEndereco)
                            )
                        )
                        .addGroup(
                          layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.TRAILING,
                              false
                            )
                            .addGroup(
                              javax.swing.GroupLayout.Alignment.LEADING,
                              layout
                                .createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addComponent(txtTelefone)
                            )
                            .addGroup(
                              javax.swing.GroupLayout.Alignment.LEADING,
                              layout
                                .createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(
                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                )
                                .addComponent(
                                  txtValDiaria,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  71,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                            )
                        )
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(
                  txtCod,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(
                  txtNome,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(
                  txtEndereco,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  txtTelefone,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  txtValDiaria,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(
                  txtTotalFat,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnConsultar)
                .addComponent(btnIncluir)
                .addComponent(btnAlterar)
                .addComponent(btnExcluir)
                .addComponent(btnSair)
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void limparForm() {
    txtCod.setText(null);
    txtNome.setText(null);
    txtEndereco.setText(null);
    txtTelefone.setText(null);
    txtValDiaria.setText(null);
    txtTotalFat.setText(null);

    txtCod.setEnabled(true);
    txtNome.setEnabled(false);
    txtTelefone.setEnabled(false);
    txtEndereco.setEnabled(false);
    txtValDiaria.setEnabled(false);
    txtTotalFat.setEnabled(false);

    txtCod.requestFocus();
    btnConsultar.setEnabled(true);
    btnIncluir.setEnabled(false);
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
  }

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnConsultarActionPerformed
    // TODO add your handling code here:
    hotel = null;
    hotel = daoHotel.consultar(Integer.parseInt(txtCod.getText()));
    if (hotel == null) {
      //não encontrou o objeto na BD
      System.out.println("vai toma no cu");
      txtCod.setEnabled(false);
      txtNome.setEnabled(true);
      txtTelefone.setEnabled(true);
      txtEndereco.setEnabled(true);
      txtValDiaria.setEnabled(true);
      txtTotalFat.setEnabled(false);

      btnConsultar.setEnabled(false);
      btnIncluir.setEnabled(true);
      btnAlterar.setEnabled(false);
      btnExcluir.setEnabled(false);
    } else {
      //encontrou o objeto na BD
      txtNome.setText(hotel.getNome());
      txtEndereco.setText(hotel.getEndereco());
      txtTelefone.setText(hotel.getTelefone());
      txtValDiaria.setText(hotel.getValorDiaria());
      txtTotalFat.setText(hotel.getTotalFaturamento());

      txtCod.setEnabled(false);
      txtNome.setEnabled(true);
      txtEndereco.setEnabled(true);
      txtTelefone.setEnabled(true);
      txtValDiaria.setEnabled(true);
      txtTotalFat.setEnabled(false);
      txtNome.requestFocus();
      btnConsultar.setEnabled(false);
      btnIncluir.setEnabled(false);
      btnAlterar.setEnabled(true);
      btnExcluir.setEnabled(true);
    }
  } //GEN-LAST:event_btnConsultarActionPerformed

  private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnIncluirActionPerformed
    // TODO add your handling code here:
    hotel = new Hotel(Integer.parseInt(txtCod.getText()), txtNome.getText());
    hotel.setEndereco(txtEndereco.getText());
    hotel.setTelefone(txtTelefone.getText());
    hotel.setValorDiaria(txtValDiaria.getText());
    daoHotel.inserir(hotel);

    //Incializando a GUI
    limparForm();
  } //GEN-LAST:event_btnIncluirActionPerformed

  private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnAlterarActionPerformed
    // TODO add your handling code here:
    if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
      //Sim
      hotel.setNome(txtNome.getText());
      hotel.setEndereco(txtEndereco.getText());
      hotel.setTelefone(txtTelefone.getText());
      hotel.setValorDiaria(txtValDiaria.getText());

      daoHotel.alterar(hotel);
    }

    //Ajusta a gui para uma nova operação de consulta

    limparForm();
  } //GEN-LAST:event_btnAlterarActionPerformed

  private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnExcluirActionPerformed
    // TODO add your handling code here:
    if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
      daoHotel.excluir(hotel);
      hotel = null;
    }

    // Limpa os campos e ajusta a GUI para uma nova operação de consulta
    limparForm();
  } //GEN-LAST:event_btnExcluirActionPerformed

  private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_btnSairActionPerformed
    // TODO add your handling code here:
    dispose();
  } //GEN-LAST:event_btnSairActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {
    //GEN-FIRST:event_formWindowOpened

    prepCon = new PreparaConexao("C##ESTUDANTE", "14112005");
    prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
    prepCon.setConnectionString("jdbc:oracle:thin:@127.0.0.1:1521:xe");
    daoHotel = new DaoHotel(prepCon.abrirConexao());
  } //GEN-LAST:event_formWindowOpened

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GuiCadastroHotel.class.getName()).log(
        java.util.logging.Level.SEVERE,
        null,
        ex
      );
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GuiCadastroHotel.class.getName()).log(
        java.util.logging.Level.SEVERE,
        null,
        ex
      );
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GuiCadastroHotel.class.getName()).log(
        java.util.logging.Level.SEVERE,
        null,
        ex
      );
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GuiCadastroHotel.class.getName()).log(
        java.util.logging.Level.SEVERE,
        null,
        ex
      );
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new GuiCadastroHotel().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAlterar;
  private javax.swing.JButton btnConsultar;
  private javax.swing.JButton btnExcluir;
  private javax.swing.JButton btnIncluir;
  private javax.swing.JButton btnSair;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField txtCod;
  private javax.swing.JTextField txtEndereco;
  private javax.swing.JTextField txtNome;
  private javax.swing.JTextField txtTelefone;
  private javax.swing.JTextField txtTotalFat;
  private javax.swing.JTextField txtValDiaria;
  // End of variables declaration//GEN-END:variables
  private Hotel hotel;
  private DaoHotel daoHotel;
  private PreparaConexao prepCon;
}
